<a href="https://colab.research.google.com/github/linhoangce/pytorch_crash_course/blob/main/fundamental_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

## Creating a tensor with shape (7, 7)

In [2]:
x = torch.rand(7, 7)
x, x.shape

(tensor([[5.5806e-01, 5.2223e-01, 4.5548e-01, 4.5056e-01, 8.0380e-01, 4.1528e-01,
          7.3503e-01],
         [9.2096e-01, 2.9205e-01, 6.7716e-03, 1.8952e-01, 8.4296e-01, 4.5395e-01,
          5.3295e-01],
         [4.3641e-01, 5.2626e-02, 6.4297e-02, 2.0089e-01, 9.8469e-01, 3.1827e-01,
          4.7220e-01],
         [6.7288e-04, 7.0313e-01, 1.0021e-01, 8.5566e-01, 5.4543e-01, 5.4132e-01,
          9.1267e-01],
         [1.5919e-01, 8.3670e-01, 1.9544e-02, 5.4407e-01, 1.9586e-01, 1.3710e-02,
          6.8203e-01],
         [2.3225e-01, 4.1663e-01, 3.4217e-01, 6.0002e-01, 9.7438e-01, 4.9423e-01,
          1.9499e-01],
         [8.6962e-01, 5.5451e-01, 8.9064e-01, 2.6943e-01, 8.3985e-01, 2.2111e-01,
          3.4568e-03]]),
 torch.Size([7, 7]))

3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7)

In [3]:
y = torch.rand(1, 7)
y

tensor([[0.7849, 0.8634, 0.0867, 0.5700, 0.7796, 0.6620, 0.0718]])

In [4]:
result = torch.matmul(x, y.T)
result, result.shape

(tensor([[2.1396],
         [2.0796],
         [1.5203],
         [1.9531],
         [1.3699],
         [2.0145],
         [2.1935]]),
 torch.Size([7, 1]))

4. Set the random seed to 0 and do 2 & 3 over again.


In [5]:
torch.manual_seed(0)
x = torch.rand(7, 7)
x

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

In [6]:
y = torch.rand(1, 7)

torch.matmul(x, y.T), torch.matmul(x, y.T).shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

Setting ramdom seed on GPU

In [7]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [15]:
torch.manual_seed(1234)
a = torch.rand(2, 3).to(device)
b = torch.rand(2, 3).to(device)

a, b


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [16]:
X = torch.matmul(a, b.T)
X, X.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

In [17]:
# find max
torch.max(X)

tensor(0.5617, device='cuda:0')

In [18]:
# find min
X.min()

tensor(0.3647, device='cuda:0')

Make a random tensor with shape (1, 1, 1, 10)

In [19]:
torch.manual_seed(7)
g = torch.rand(1, 1, 1, 10)
g, g.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]))

In [20]:
g_squeezed = torch.squeeze(g)
g_squeezed

tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])